feat: new brand multiprocesses feature
53jk1/distributed-cipher-cracking pull request #3
Opened 2022-02-23 23:56 UTC by Desukiteru

fuck my ass

2022-02-24 07:40 UTC, 53jk1 commented
Resolve conflicts

2022-02-26 22:08 UTC, 53jk1 commented
Check this out

2022-02-26 22:25 UTC, kbakdev requested changes

2022-02-26 22:25 UTC, kbakdev commented on .github/workflows/python-app.yml
> -        pytest
A very creative solution to a problem

2022-02-26 22:25 UTC, kbakdev commented on main.py
> +class findings:
I think there are too few public methods

2022-02-26 22:25 UTC, kbakdev commented on main.py
> +def next(string):
We are redefining built-in `next` func

2022-02-26 22:25 UTC, kbakdev commented on main.py
> +def next(string):
Otherwise, we're redefining name `string` from outer scope.

2022-02-26 22:25 UTC, kbakdev commented on main.py
>              break
No exception type specified

2022-02-26 22:25 UTC, kbakdev commented on main.py
> +def findMe(jakisint):
Too many branches

2022-02-26 22:25 UTC, kbakdev commented on main.py
> +    map = {}
Redefining built-in `map`

2022-02-26 22:25 UTC, kbakdev commented on main.py
> +def sortMe(list):
Redefining built-in `list`

2022-02-26 22:25 UTC, kbakdev commented on main.py
>  def codeMe(data, key):
Redefining name `data` and `key` for outer scope

2022-02-26 22:25 UTC, kbakdev commented on main.py
> +def deCodeMe(data, key):
Redefining name `data` and `key` for outer scope

2022-02-26 22:25 UTC, kbakdev commented on main.py
> +            record = findings()
Redefining name `record` from outer scope

2022-02-26 22:25 UTC, kbakdev commented on main.py
> +def prepere(number, chipher):
Redefining `chiper` from outer scope

2022-02-26 22:25 UTC, kbakdev commented on main.py
> +    p = multiprocessing.Pool(coreNumber)
Consider using `with` for resource-allocating operations.

2022-02-26 22:25 UTC, 53jk1 commented on main.py
> +class findings:
btw, class name `findings` doesn't conform to PascalCase naming style

2022-02-26 22:25 UTC, kbakdev commented on main.py
> +class frame:
Class name `frame` doesn't conform to PascalCase naming style

2022-02-26 22:25 UTC, kbakdev commented on main.py
> +    def lenMe(self):
Method name `lenMe` doesn't conform to snake_case naming style

2022-02-26 22:25 UTC, kbakdev commented on main.py
> +    def boutMe(self):
Method name `boutMe` doesn't conform to snake_case naming style

2022-02-26 22:25 UTC, 53jk1 commented on main.py
>  def characterToIndex(char):
Function name `characterToIndex` doesn't conform to snake_case naming style

2022-02-26 22:25 UTC, kbakdev commented on main.py
>  def indexToCharacter(index):
Function name `indexToCharacter` doesn't conform to snake_case naming style

2022-02-26 22:25 UTC, 53jk1 commented on main.py
>  def parseMe(array):
Function name `parseMe` doesn't conform to snake_case naming style

2022-02-26 22:25 UTC, 53jk1 commented on main.py
> +def findMe(jakisint):
Function name `findMe` doesn't conform to snake_case naming style

2022-02-26 22:25 UTC, kbakdev commented on main.py
> +    for i in map:
Consider iterating with `.items()`

2022-02-26 22:25 UTC, 53jk1 commented on main.py
> +    for i in range(len(buffor)):
Consider using enumerate instead of iterating with range and len

2022-02-26 22:25 UTC, 53jk1 commented on main.py
> +    workString = str(test)
Variable name `workString` doesn't conform to snake_case naming style

2022-02-26 22:25 UTC, 53jk1 commented on main.py
> +        workString = "0"+workString
Variable name `workString` doesn't conform to snake_case naming style

2022-02-26 22:25 UTC, 53jk1 commented on main.py
> +        workString = ("00"*(i))+workString
Variable name `workString` doesn't conform to snake_case naming style

2022-02-26 22:25 UTC, 53jk1 commented on main.py
> +def sortMe(list):
Function name `sortMe` doesn't conform to snake_case naming style

2022-02-26 22:25 UTC, 53jk1 commented on main.py
>  def codeMe(data, key):
Function name `codeMe` doesn't conform to snake_case naming style

2022-02-26 22:25 UTC, 53jk1 commented on main.py
> +def deCodeMe(data, key):
Function name `deCodeMe` doesn't conform to snake_case naming style

2022-02-26 22:25 UTC, 53jk1 commented on main.py
> +def begin(pp):
Maybe another name of var for `pp`?

2022-02-26 22:25 UTC, 53jk1 commented on main.py
> +    fr = frame()
Maybe another name of var for `fr`?

2022-02-26 22:25 UTC, 53jk1 commented on main.py
> +    ts = time.time()
Maybe another name of var for `ts`?

2022-02-26 22:25 UTC, 53jk1 commented on main.py
> +        bar = {
I think `bar` is disallowed name

2022-02-26 22:25 UTC, 53jk1 commented on main.py
> +    data = "0"
Constant name `data` doesn't conform to UPPER_CASE naming style

2022-02-26 22:25 UTC, 53jk1 commented on main.py
> +    key = "0"
Constant name `key` doesn't conform to UPPER_CASE naming style

2022-02-26 22:25 UTC, 53jk1 commented on main.py
> +    numberOfCycles = 1
Constant name `numberOfCycles` doesn't conform to UPPER_CASE naming style

2022-02-26 22:25 UTC, 53jk1 commented on main.py
> +
Trailing whitespace

2022-02-26 22:25 UTC, 53jk1 commented on main.py
> +
Trailing whitespace

2022-02-26 22:25 UTC, 53jk1 commented on main.py
> +
Trailing newlines

2022-02-26 22:28 UTC, Desu-potato commented on main.py
> +class findings:
naming style to fix, i think we are good with methods

2022-02-26 22:28 UTC, Desukiteru commented on main.py
> +def next(string):
eeeee k

2022-02-26 22:29 UTC, Desukiteru commented on main.py
> +def findMe(jakisint):
to fix

2022-02-26 22:29 UTC, Desukiteru commented on main.py
> +
what?

2022-02-27 12:27 UTC, merged